# Site settings
title: FCardinaux
email: your-email@domain.com

# Write an awesome description for your new site here. 
# It will appear in your document head meta (for Google search results) 
# and in your feed.xml site description.
description: > # this means to ignore newlines until "baseurl:"
  CV, project notes, 
  useful lists, etc.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://yourdomain.com" # the base hostname & protocol for your site

twitter_username: fcardinaux
github_username:  fcardinaux

# Build settings
markdown: kramdown

